services:
  db:
    image: postgres:17-alpine
    container_name: newsletter
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - newsletter_pg_data:/var/lib/postgresql/data
      - ./docker/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

volumes:
  newsletter_pg_data:
